/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ardrone.Sensores;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Johnnatan
 */
public class LogGUI extends javax.swing.JFrame {
    
    private boolean active;

    /**
     * Creates new form LogGUI
     */
    public LogGUI() {
        initComponents();
        active = true;
        executeLogs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Log_Battery = new javax.swing.JLabel();
        jLabel_Log_Altitude = new javax.swing.JLabel();
        jLabel_Log_Longitude = new javax.swing.JLabel();
        jLabel_Log_Vx = new javax.swing.JLabel();
        jLabel_Log_Vz = new javax.swing.JLabel();
        jLabel_Log_Yaw = new javax.swing.JLabel();
        jLabel_Log_Sequence = new javax.swing.JLabel();
        jLabel_Log_Roll = new javax.swing.JLabel();
        jLabel_Log_Pitch = new javax.swing.JLabel();
        jLabel_Log_Battery_Value = new javax.swing.JLabel();
        jLabel_Log_Altitude_Value = new javax.swing.JLabel();
        jLabel_Log_Longitude_Value = new javax.swing.JLabel();
        jLabel_Log_Pitch_Value = new javax.swing.JLabel();
        jLabel_Log_Roll_Value = new javax.swing.JLabel();
        jLabel_Log_Sequence_Value = new javax.swing.JLabel();
        jLabel_Log_Vx_Value = new javax.swing.JLabel();
        jLabel_Log_Vz_Value = new javax.swing.JLabel();
        jLabel_Log_Yaw_Value = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Logs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 0, 0)));

        jLabel_Log_Battery.setText("Battery");

        jLabel_Log_Altitude.setText("Altitude");

        jLabel_Log_Longitude.setText("Longitude");

        jLabel_Log_Vx.setText("Vx");

        jLabel_Log_Vz.setText("Vz");

        jLabel_Log_Yaw.setText("Yaw");

        jLabel_Log_Sequence.setText("Sequence");

        jLabel_Log_Roll.setText("Roll");

        jLabel_Log_Pitch.setText("Pitch");

        jLabel_Log_Battery_Value.setText("100");

        jLabel_Log_Altitude_Value.setText("6.00");

        jLabel_Log_Longitude_Value.setText("0.000");

        jLabel_Log_Pitch_Value.setText("0.000");

        jLabel_Log_Roll_Value.setText("0.000");

        jLabel_Log_Sequence_Value.setText("10000000");

        jLabel_Log_Vx_Value.setText("0.000");

        jLabel_Log_Vz_Value.setText("0.000");

        jLabel_Log_Yaw_Value.setText("0.000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Log_Battery)
                    .addComponent(jLabel_Log_Battery_Value))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Log_Altitude)
                    .addComponent(jLabel_Log_Altitude_Value))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Log_Longitude)
                    .addComponent(jLabel_Log_Longitude_Value))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Log_Pitch)
                    .addComponent(jLabel_Log_Pitch_Value))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Log_Roll)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel_Log_Sequence))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Log_Roll_Value)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Log_Sequence_Value)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Log_Vx)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel_Log_Vz))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Log_Vx_Value)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Log_Vz_Value)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Log_Yaw_Value)
                    .addComponent(jLabel_Log_Yaw))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Log_Battery)
                    .addComponent(jLabel_Log_Altitude)
                    .addComponent(jLabel_Log_Longitude)
                    .addComponent(jLabel_Log_Pitch)
                    .addComponent(jLabel_Log_Roll)
                    .addComponent(jLabel_Log_Sequence)
                    .addComponent(jLabel_Log_Vx)
                    .addComponent(jLabel_Log_Vz)
                    .addComponent(jLabel_Log_Yaw))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Log_Battery_Value)
                    .addComponent(jLabel_Log_Altitude_Value)
                    .addComponent(jLabel_Log_Longitude_Value)
                    .addComponent(jLabel_Log_Pitch_Value)
                    .addComponent(jLabel_Log_Roll_Value)
                    .addComponent(jLabel_Log_Sequence_Value)
                    .addComponent(jLabel_Log_Vx_Value)
                    .addComponent(jLabel_Log_Vz_Value)
                    .addComponent(jLabel_Log_Yaw_Value))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new LogGUI().setVisible(true);
            }
        });
    }
    
    private void executeLogs() {
        new Thread(new Runnable() {
            
            @Override
            public void run() {
                while (active) {
                    jLabel_Log_Battery_Value.setText(String.valueOf(Sensores.getBattery()));
                    jLabel_Log_Altitude_Value.setText(String.valueOf(Sensores.getAltitude()));
                    jLabel_Log_Longitude_Value.setText(String.valueOf(Sensores.getLongitude()));
                    jLabel_Log_Pitch_Value.setText(String.valueOf(Sensores.getPitch()));
                    jLabel_Log_Roll_Value.setText(String.valueOf(Sensores.getRoll()));
                    jLabel_Log_Sequence_Value.setText(String.valueOf(Sensores.getSequence()));
                    jLabel_Log_Vx_Value.setText(String.valueOf(Sensores.getVx()));
                    jLabel_Log_Vz_Value.setText(String.valueOf(Sensores.getVz()));
                    jLabel_Log_Yaw_Value.setText(String.valueOf(Sensores.getYaw()));
                    
                    try {
                        Thread.sleep(300);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(LogGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
        
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    
    public boolean getActive() {
        return this.active;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Log_Altitude;
    private javax.swing.JLabel jLabel_Log_Altitude_Value;
    private javax.swing.JLabel jLabel_Log_Battery;
    private javax.swing.JLabel jLabel_Log_Battery_Value;
    private javax.swing.JLabel jLabel_Log_Longitude;
    private javax.swing.JLabel jLabel_Log_Longitude_Value;
    private javax.swing.JLabel jLabel_Log_Pitch;
    private javax.swing.JLabel jLabel_Log_Pitch_Value;
    private javax.swing.JLabel jLabel_Log_Roll;
    private javax.swing.JLabel jLabel_Log_Roll_Value;
    private javax.swing.JLabel jLabel_Log_Sequence;
    private javax.swing.JLabel jLabel_Log_Sequence_Value;
    private javax.swing.JLabel jLabel_Log_Vx;
    private javax.swing.JLabel jLabel_Log_Vx_Value;
    private javax.swing.JLabel jLabel_Log_Vz;
    private javax.swing.JLabel jLabel_Log_Vz_Value;
    private javax.swing.JLabel jLabel_Log_Yaw;
    private javax.swing.JLabel jLabel_Log_Yaw_Value;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
